[package]
name = "chat_zone"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1",  features = ["derive"]}

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"