[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common =  { path = "../common" }
tokio = {version = "1", features= ["full"]}
uuid = { version = "1", features = ["v4"] }
regex = "1"

[[bin]]
name = "client"
path = "source/main.rs"
